# Site settings
title: Michael Clyde Hall
email: mike.clyde.hall@gmail.com
url: https://mikehall.co.za
description: ""
skills: ".NET Software Engineer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 333333
  accent: 0099e5
  text: FFF

# Footer settings
footer:
  copyright: Michael Hall

# Build settings
markdown: kramdown
permalink: pretty
