# Site settings
title: Michael Clyde Hall
email: mike.clyde.hall@gmail.com
url: https://mchall.github.io
description: ""
skills: "Senior Software Engineer"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00b6de #80B3FF
  primary-rgb: "0,182,222" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Michael Hall

# Build settings
markdown: kramdown
permalink: pretty
