# Site settings
title: Michael Clyde Hall
email: mike.clyde.hall@gmail.com
url: https://mikehall.co.za
description: ""
skills: "Senior Software Engineer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0099e5
  secondary: 111111
  secondary-dark: 111111

# Footer settings
footer:
  copyright: Michael Hall

# Build settings
markdown: kramdown
permalink: pretty
